### ISSUE TITLE
Chest models keep breaking.

### ISSUE THREAD

**Issue by forkiesassds** [TeamQuantumFusion/DashLoader#1]
Possible incompatibility with Enhanced Block Entities?
![image](https://user-images.githubusercontent.com/54495659/148289429-066df2fc-d278-4761-98cd-4e68717f7579.png)
I attached the logs here. [latest.log](https://github.com/QuantumFusionMC/DashLoader-Core/files/7817814/latest.log)

**Comment by Scarlaid** [comment]
Try putting the **Fabric Resources** on top of your resource pack, might work out
I have been messing around and shuffle the resource packs and yeah it just worked 👀

A Head-up: Yep it also worked flawlessly with EnhancedBlockEntities
![image](https://user-images.githubusercontent.com/90851437/152664244-edf1cee8-2f5e-419c-8816-45d7cf0bbad6.png)
![image](https://user-images.githubusercontent.com/90851437/152664267-64a9d5b5-f083-4d9f-81b0-a95eb86100bc.png)

**Comment by forkiesassds** [comment]
> Try putting the **Fabric Resources** on top of your resource pack, might work out I have been messing around and shuffle the resource packs and yeah it just worked 👀
> 
> A Head-up: Yep it also worked flawlessly with EnhancedBlockEntities ![image](https://user-images.githubusercontent.com/90851437/152664244-edf1cee8-2f5e-419c-8816-45d7cf0bbad6.png) ![image](https://user-images.githubusercontent.com/90851437/152664267-64a9d5b5-f083-4d9f-81b0-a95eb86100bc.png)

With fabric mod resources on top it still happens.
Note: It happens after you restart the game.
![image](https://user-images.githubusercontent.com/54495659/152983399-73015d93-4505-4614-bdb5-10349bd87ea9.png)

**Comment by alphaqu** [comment]
Switching the resourcepacks just made dashloader recache because you never used that configuration before. If you press f3 + t where dashloader loads from cache it will become borked again. 

EBE has a pull request which will soon be merged that adds support for DashLoader.

**Comment by Scarlaid** [comment]
Make sense, it's just a waiting game then.

**Comment by alphaqu** [comment]
EBE is supported on dashloader 3.0+, 4.0 has broken it but compat will be soon added again.
