### ISSUE TITLE
sodium (1.18.x/next branch) doesnt work with dashloader

### ISSUE THREAD

**Issue by CheesyTheArtist** [TeamQuantumFusion/DashLoader#2]
Sodium's 1.18.x/next branch makes dashloader crash the game when loading in the cache. Doesnt make dashloader crash the game when its making the cache.

how to reproduce:
![image](https://user-images.githubusercontent.com/69735314/148393928-8e854036-6a1a-4043-a34d-78c40b47973b.png)

Log: https://paste.ee/p/JHANz

**Comment by TheAirBlow** [comment]
paste not found lol

**Comment by alphaqu** [comment]
Cheezy stop doing art
